### ISSUE TITLE
Post params should not allow array of slugs

### ISSUE THREAD

**Issue by alexisdouheret** [AfterShip/aftership-sdk-nodejs#108]
I guess this is legacy since the API seems to allow an array but then labels the slug as unrecognized
![image](https://github.com/AfterShip/aftership-sdk-nodejs/assets/32124592/52021e05-8ab9-4a67-832d-eb4da785d005)

https://github.com/AfterShip/aftership-sdk-nodejs/blob/ad421a5b2c6a991cea43b9219b29f11da4054164/src/model/tracking/tracking_create_params.ts#L43-L50

**Comment by panxl6** [comment]
This is a historical issue. Please limit user input and make sure that `slug` parameter is a string and not an array. Our refactored version is coming soon.
