### ISSUE TITLE
Very bad practice to overwrite `call` method

### ISSUE THREAD

**Issue by benbuckman** [AfterShip/aftership-sdk-nodejs#19]
The `call` method is a native JS primitive, used for [calling a function with a particular scope](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call).

The 4.x branch of this module, unfortunately, overwrites `.call` to make API calls. Overriding native methods (without a very good reason) is a bad practice in general. Other code (like test stubs) might assume that `.call` behaves the normal way and break. Or a developer looking at the code could think that `Aftership.call` is calling the function `Aftership` with a particular context. And if someone did want to use `.call` the normal way, `Aftership.call.call` looks pretty weird.

Is there a reason the native function was overridden?
Perhaps in the next major release, it could be renamed to `request` or some similarly non-native name?

Thank you!

**Comment by JChanceHud** [comment]
Any progress on this?

**Comment by csulit** [comment]
Any update on this?

**Comment by Bossa573** [comment]
closing this ticket in favor of 6.0.0 release, everyone please take a look and try it out.
