### ISSUE TITLE
please allow yarn installations

### ISSUE THREAD

**Issue by bonesoul** [AfterShip/aftership-sdk-nodejs#21]
currently the new yarn package manager (https://yarnpkg.com/) results with an error;

```
error aftership@5.3.3: The engine "node" is incompatible with this module. Expected version "4.2.3".
error Found incompatible module
```

my pr fixes this; https://github.com/AfterShip/aftership-sdk-nodejs/pull/20
please consider it.

**Comment by rafadc** [comment]
Just for the reference. As a workaround you can just

```
npm install aftership --save
```

And continue using yarn

**Comment by nbeydoon** [comment]
this workaround isn't viable in production, why not just put a correct engine in the package.json?

**Comment by foray1010** [comment]
thanks for report, I will fix asap

**Comment by foray1010** [comment]
`5.3.4` should fixed this problem
https://github.com/AfterShip/aftership-sdk-nodejs/commit/a78abc84bac69fa354fe1929a77425077a2b07f4
