### ISSUE TITLE
please update qs package

### ISSUE THREAD

**Issue by bonesoul** [AfterShip/aftership-sdk-nodejs#22]
Prototype Override Protection Bypass

IN PACKAGE	VERSION	SUB PACKAGE VERSION	CWE	CVSSV3
aftership	5.3.3	6.3.0	CWE-20	CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N

https://github.com/ljharb/qs/blob/master/CHANGELOG.md#640

**Comment by Bossa573** [comment]
`request` module has been updated and it's using `qs` 6.5.x now
