### ISSUE TITLE
Delivery status types are number, but should be strings

### ISSUE THREAD

**Issue by lesauf** [AfterShip/aftership-sdk-nodejs#59]
Hello,

Thank you for the nice job.

I am using this to fetch trackings, but I am not able to filter by tag (delivery status) because the types do not match.

For example, in delivery_status.d.ts the types are number, but on the documentation (https://docs.aftership.com/api/4/trackings/get-trackings) they are supposed to be strings :

> Current status of tracking. Values include Pending,  InfoReceived, ...

Please can you have a look at that?

Thank you,
Stephane

**Comment by Bossa573** [comment]
Hello,

Thanks for the reporting and we are investigating the issue,
we will update here when more information available

**Comment by Bossa573** [comment]
We have released 7.0.0 to resolve this issue.
https://github.com/AfterShip/aftership-sdk-nodejs/releases/tag/7.0.0

Major version is bumped due to breaking change.
