### ISSUE TITLE
tracking_number present in tracking object.

### ISSUE THREAD

**Issue by millnitzluan** [AfterShip/aftership-sdk-nodejs#70]
Looking into the [Tracking Object documentation](https://developers.aftership.com/reference/object-tracking) the endpoint returns the `tracking_number`, but looking into the [Tracking Interface](https://github.com/AfterShip/aftership-sdk-nodejs/blob/5277e2a0d6eb338f9631203fe6d9ead5b2ce0a7a/src/model/tracking/tracking.ts#L8) it's not typing the `tracking_number`. Is it a bug or something that intentional?

**Comment by Bossa573** [comment]
Hello, sorry for the delayed response and this has been fixed under https://github.com/AfterShip/aftership-sdk-nodejs/releases/tag/7.0.3
