### ISSUE TITLE
tracking_numbers parameter missing from MultiTrackingsQueryParams 

### ISSUE THREAD

**Issue by gbillig** [AfterShip/aftership-sdk-nodejs#80]
Looking at the documentation for [`Get Trackings`](https://developers.aftership.com/reference/get-trackings), I see that it is possible to call this endpoint with a query parameter called `tracking_numbers` to search by tracking number. However in this library, the typing of `MultiTrackingsQueryParams` is missing this parameter.

Could you please add it? Thanks!

**Comment by gbillig** [comment]
I see that there is an open PR that would resolve my issue: https://github.com/AfterShip/aftership-sdk-nodejs/pull/79

**Comment by foamzou** [comment]
Hi  @gbillig 
The tracking_numbers parameter has been added in the latest version.
Please update and check it.
