### ISSUE TITLE
Function addNotification save email as customer instead of subscriber

### ISSUE THREAD

**Issue by joserocha3** [AfterShip/aftership-sdk-nodejs#90]
Calling `aftership.notification.addNotification` with `emails` saves the submitted emails under the Customer section instead of Subscribers section.

I submitted `pablo@whiterabbitjapan.com` using `aftership.notification.addNotification` and it shows up under the customer.

![image](https://user-images.githubusercontent.com/11415340/220821808-6bcc8688-4d39-419f-8a46-4751d2af97ba.png)

Please not that using the [tracking page](https://track.whiterabbitjapan.com) the email is saved to the Subscribers section as expected.

**Comment by tallguys** [comment]
hi @joserocha3,
I am the engineer from AfterShip. The add notification behavior follows this [API](https://www.aftership.com/docs/tracking/47839ec6872a2-add-a-notification-by-tracking-id). It updates the emails of the customer.

We don't support updating the subscribed emails by the API as of now. Mostly, it adds by the end users as the behavior on the tracking page you see.

We will consider adding this feature in the future. Thanks for the advice.

**Comment by joserocha3** [comment]
@tallguys thank you for the reply!

Does adding the email to the customer record setup that email to receive tracking update notifications? Or is using the [tracking page](https://track.whiterabbitjapan.com/) the only way so add an email to receive updates?

**Comment by joserocha3** [comment]
@tallguys I added my email to some customer records and I never received an update notification. 

The API docs say "Add notification receivers to a tracking number", which the API does not do.

I believe this issue should be reopened because `aftership.notification.addNotification` and the API are both misleading. One of these needs to happen:

- the API needs to be updated to add "Subscribers" instead of adding an email to the customer record
- be properly documented and renamed to explain that it adds an email to the customer record not a notification receiver to a tracking number
- the API and function removed (maybe temporarily until it does what the docs say)

![image](https://user-images.githubusercontent.com/11415340/221724276-2e1a421b-12f5-4702-bf84-fd6ce8c94f56.png)

**Comment by Bossa573** [comment]
@joserocha3
if you add emails or phone numbers to a `tracking` resource via `POST https://api.aftership.com/v4/notifications/{tracking_id}/add`, it should be able to send notifications to the email or phone number you added, and it would send the notifications to **customers**, not **subscribers**, thus please make sure you enable the proper email flow in https://admin.aftership.com/notifications/setting.

Also please submit a ticket to support@aftership.com for further clarification if needed, thank you very much.
