### ISSUE TITLE
Models not updated

### ISSUE THREAD

**Issue by jovicailievski** [AfterShip/aftership-sdk-nodejs#92]
The models are not updated with the new api fields.

**Comment by Beaelf** [comment]
Hello,  Thanks for your feedback, would you like to tell us which endpoint are not updated?

**Comment by Beaelf** [comment]
> You models are not updated with the new api fields.

Hello, Thanks for your feedback, would you like to tell us which endpoint are not updated?

**Comment by jovicailievski** [comment]
For example CourierDetectTracking is missing 
destination_country_iso3, tracking_state, origin_country_iso3 and more. Also i noticed some missing in TrackingCreate.

**Comment by jovicailievski** [comment]
Actually all new fields everywhere are not updated

**Comment by Beaelf** [comment]
> For example CourierDetectTracking is missing destination_country_iso3, tracking_state, origin_country_iso3 and more. Also i noticed some missing in TrackingCreate.

Thanks, We'll check in the next few days and update the sdk fields as soon as possible

**Comment by Bossa573** [comment]
the model should be updated, please feel free to reopen this ticket if needed
